FROM node:lts-alpine3.23
LABEL org.opencontainers.image.source="https://github.com/LibreTexts/shapeshift"

WORKDIR /usr/src/shapeshift

# Install prod deps first for better caching
COPY package*.json ./
RUN npm install

# Build
COPY . .
RUN npm run build

ENTRYPOINT ["node", "build/workers/api.js"]