FROM ghcr.io/puppeteer/puppeteer:latest
LABEL org.opencontainers.image.source="https://github.com/LibreTexts/shapeshift"

WORKDIR /usr/src/shapeshift

# Install prod deps first for better caching
COPY package*.json ./
RUN npm ci

# Build
COPY . .
RUN npm run build

# Puppeteer image sets up Chrome; no executablePath needed
ENTRYPOINT ["node", "build/workers/processor.js"]